// <auto-generated />
using System;
using EFCoreWebDemo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TodoApi.Migrations
{
    [DbContext(typeof(EFCoreWebDemoContext))]
    [Migration("20180625192703_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreWebDemo.ListDetails", b =>
                {
                    b.Property<int>("DetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Checked");

                    b.Property<string>("Description");

                    b.Property<int?>("ListNameListId");

                    b.HasKey("DetailID");

                    b.HasIndex("ListNameListId");

                    b.ToTable("ListDetails");
                });

            modelBuilder.Entity("EFCoreWebDemo.ListName", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("ListId");

                    b.ToTable("ListName");
                });

            modelBuilder.Entity("EFCoreWebDemo.ListDetails", b =>
                {
                    b.HasOne("EFCoreWebDemo.ListName")
                        .WithMany("ListDetail")
                        .HasForeignKey("ListNameListId");
                });
#pragma warning restore 612, 618
        }
    }
}
